# 2 vCPU latency config
CONFIG_NAME="2vcpu_1w"
PAIR_FILE="tooling/pairs/pairs_20.json"
NUM_PEERS=20
HD_WORKERS=1
HD_FLAGS="--tls --metrics-port 9090"
LATENCY_RUNS=10
PING_COUNT=5000
PING_WARMUP=500
MSG_SIZE=1400
